name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to authenticate with GitHub Packages
      contents: read # Needed to read the contents of the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout the code from the repository

    - name: Setup Google Cloud SDK # Install the Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main # Install the Google Cloud SDK
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }} # The GCP project ID
        service_account_key: ${{ secrets.GCP_SA_KEY }} # The GCP service account key
        export_default_credentials: true

    - name: Authenticate Google Cloud SDK # Authenticate the Google Cloud SDK with the service account key
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }} # The GCP service account key

    - name: Deploy to Google Cloud Functions # Deploy the Cloud Function
      run: |
        cd functions
        gcloud functions deploy cloud-function-deployment-v2 --runtime nodejs14 --trigger-http --region us-central1 --allow-unauthenticated
