name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to authenticate with GitHub Packages
      contents: read # Needed to read the contents of the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Google Cloud SDK
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Google Cloud Functions
      run: |
        cd functions
        gcloud iam service-accounts add-iam-policy-binding ***@appspot.gserviceaccount.com --member='serviceAccount:gcp-cloud-function-copilot-v2@***.iam.gserviceaccount.com' --role='roles/iam.serviceAccountUser'
        gcloud functions deploy cloud-function-deployment-v2 --runtime nodejs18 --trigger-http --region us-central1 --allow-unauthenticated